# Generated by Django 5.2.9 on 2026-01-05 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_interrogacion', models.IntegerField(default=60, help_text='Tiempo entre pings en segundos')),
                ('reintentos', models.IntegerField(default=3, help_text='Número de reintentos antes de marcar offline')),
                ('umbral_falla_fibra', models.IntegerField(default=60, help_text='Tiempo offline para alerta Fibra (segundos)')),
                ('umbral_falla_celular', models.IntegerField(default=300, help_text='Tiempo offline para alerta Celular (segundos)')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.CharField(max_length=50, unique=True, verbose_name='ID Equipo')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('en_mantenimiento', models.BooleanField(default=False)),
                ('medio_comunicacion', models.CharField(choices=[('FIBRA', 'Fibra Óptica'), ('CELULAR', 'Celular (4G/5G)')], default='FIBRA', max_length=20)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('poste', models.CharField(blank=True, max_length=50, null=True)),
                ('piloto', models.CharField(blank=True, max_length=100, null=True)),
                ('canasta', models.BooleanField(default=False)),
                ('permisos', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.marca')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.tipoequipo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latencia_ms', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('TIMEOUT', 'Timeout'), ('MAINTENANCE', 'Mantenimiento')], max_length=20)),
                ('packet_loss', models.FloatField(default=0.0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='monitor.equipo')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'equipo'], name='monitor_his_timesta_e3de03_idx')],
            },
        ),
    ]
