# Generated by Django 5.2.9 on 2026-01-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
    ]
