# Generated by Django 5.2.9 on 2026-01-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_equipo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Color HEX (e.g. #3b82f6)', max_length=7),
        ),
    ]
