# Generated by Django 5.2.9 on 2026-01-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_marca_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Color HEX para dashboards y gráficos', max_length=7),
        ),
    ]
