# Generated by Django 5.2.9 on 2026-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_marca_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='color',
            field=models.CharField(default='#6B7280', help_text='Color hexadecimal para visualización (ej: #3B82F6)', max_length=7),
        ),
    ]
