# Generated by Django 5.2.9 on 2026-01-22 21:47

import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ciclofacturacion',
            name='monitor_cic_mes_anio_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='monitor_equ_is_onli_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='monitor_equ_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='monitor_equ_medio_c_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='monitor_equ_last_se_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipo',
            name='monitor_equ_online_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventofacturacion',
            name='monitor_evt_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventofacturacion',
            name='monitor_evt_tipo_ev_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventofacturacion',
            name='monitor_evt_fecha_tipo_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventofacturacion',
            name='monitor_evt_ciclo_por_idx',
        ),
        migrations.RemoveIndex(
            model_name='medidor',
            name='monitor_med_numero_idx',
        ),
        migrations.RemoveIndex(
            model_name='medidor',
            name='monitor_med_marca_idx',
        ),
        migrations.RemoveIndex(
            model_name='medidor',
            name='monitor_med_porcion_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Recibir alertas de equipos críticos por correo electrónico', verbose_name='Notificaciones por Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat de Telegram para recibir notificaciones. Para obtenerlo, habla con @userinfobot', max_length=100, null=True, verbose_name='Chat ID de Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notifications',
            field=models.BooleanField(default=False, help_text='Recibir alertas de equipos críticos por Telegram', verbose_name='Notificaciones por Telegram'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: JPG, PNG, GIF, WEBP. Tamaño máximo: 2MB', null=True, upload_to='avatars/', validators=[monitor.models.validate_avatar], verbose_name='Avatar'),
        ),
    ]
