# Generated by Django 5.2.9 on 2026-01-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('MASIVO', 'Masivo'), ('ESPECIAL', 'Especial')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Porción',
                'verbose_name_plural': 'Porciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='1-12', verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('tipo', models.CharField(choices=[('MASIVO', 'Masivo'), ('ESPECIAL', 'Especial')], max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ciclo de Facturación',
                'verbose_name_plural': 'Ciclos de Facturación',
                'ordering': ['-anio', '-mes', 'tipo'],
                'unique_together': {('mes', 'anio', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='EventoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('PREFACTURACION', 'Prefacturación'), ('FACTURACION', 'Facturación')], max_length=20, verbose_name='Tipo de Evento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='monitor.ciclofacturacion', verbose_name='Ciclo')),
                ('porcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='monitor.porcion', verbose_name='Porción')),
            ],
            options={
                'verbose_name': 'Evento de Facturación',
                'verbose_name_plural': 'Eventos de Facturación',
                'ordering': ['fecha', 'tipo_evento'],
            },
        ),
    ]
