# Generated by Django 5.2.9 on 2026-01-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_remove_ciclofacturacion_monitor_cic_mes_anio_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='snmp_auth_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Clave Autenticación'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='snmp_auth_protocol',
            field=models.CharField(choices=[('MD5', 'MD5'), ('SHA', 'SHA'), ('NONE', 'None')], default='SHA', max_length=10, verbose_name='Protocolo Autenticación'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='snmp_priv_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Clave Privacidad'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='snmp_priv_protocol',
            field=models.CharField(choices=[('DES', 'DES'), ('AES', 'AES'), ('NONE', 'None')], default='AES', max_length=10, verbose_name='Protocolo Privacidad'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='snmp_user',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Usuario SNMP v3'),
        ),
        migrations.AlterField(
            model_name='eventofacturacion',
            name='tipo_evento',
            field=models.CharField(choices=[('FACTURACION', 'Facturación')], max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.marca')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('tipo', models.CharField(choices=[('APP', 'Servidor de Aplicación'), ('NETWORK', 'Servidor de Red'), ('DB', 'Servidor de Base de Datos'), ('SECURITY', 'Servidor de Seguridad'), ('OTHER', 'Otros')], default='OTHER', max_length=20)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='monitor.sistema')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['sistema', 'nombre'],
            },
        ),
    ]
