# Generated by Django 5.2.9 on 2026-01-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_porcion_ciclofacturacion_eventofacturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Número de Medidor')),
                ('marca', models.CharField(choices=[('HONEYWELL', 'Honeywell'), ('TRILLIANT', 'Trilliant'), ('ITRON', 'Itron'), ('HEXING', 'Hexing')], max_length=20, verbose_name='Marca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('porcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='monitor.porcion', verbose_name='Porción')),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Medidores',
                'ordering': ['numero'],
            },
        ),
    ]
