# Generated by Django 5.2.9 on 2026-01-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_medidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='medio_comunicacion',
            field=models.CharField(choices=[('FIBRA', 'Fibra Óptica'), ('CELULAR', 'Celular')], default='FIBRA', max_length=20),
        ),
    ]
