# Generated by Django 5.2.9 on 2026-01-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_equipo_medio_comunicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='colector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidores_asociados', to='monitor.equipo', verbose_name='Colector Asociado'),
        ),
    ]
