# Generated by Django 5.2.9 on 2026-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_configuracionglobal_snmp_auth_key_and_more'),
        ('monitor', '0010_medidor_colector'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='cpu_usage',
            field=models.FloatField(blank=True, help_text='Porcentaje de uso de CPU', null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='disk_total',
            field=models.BigIntegerField(blank=True, help_text='Disco Total en Bytes', null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='disk_used',
            field=models.BigIntegerField(blank=True, help_text='Disco Usado en Bytes', null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='memory_total',
            field=models.BigIntegerField(blank=True, help_text='Memoria Total en Bytes', null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='memory_used',
            field=models.BigIntegerField(blank=True, help_text='Memoria Usada en Bytes', null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='uptime',
            field=models.CharField(blank=True, help_text='Tiempo de actividad del sistema', max_length=100, null=True),
        ),
    ]
